---
- name: Wait for SSH connection
  hosts: tag_Name_dev_server     # aws_ec2          # all
  gather_facts: False
  tasks:
    - name: Ensure SSH port open
      wait_for:
        port: 22
        delay: 10
        timeout: 160
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

- name: Install Docker
  hosts: tag_Name_dev_server     # aws_ec2          # all
  become: yes     # become_user: root is already the default here so don't have to include
  tasks:
    - name: Make sure Docker is installed
      yum: 
        name: docker
        update_cache: yes
        state: present
    - name: Make sure docker daemon is running  # this reformulation is one approach to best practice
      systemd:
        name: docker
        state: started

- name: Create new linux user
  hosts: tag_Name_dev_server      # aws_ec2          # all
  become: yes
  vars_files:
    - project-vars
  tasks:
    - name: Create new linux user
      user: 
        name: laura
        groups: "{{user_groups}}"


- name: Install Docker-compose
  hosts: tag_Name_dev_server       # aws_ec2          # all
  become: yes
  become_user: laura
  tasks:
    - name: docker-compose directory has been created
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install docker-compose
      get_url: 
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ remote_arch.stdout }}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x


- name: Start docker containers
  hosts: tag_Name_dev_server      # aws_ec2          # all
  become: yes
  become_user: laura
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker-compose file
      copy:
        src: /home/laura/twnsubs/15-ansible-sst-subm/docker-compose-full.yaml
        dest: /home/laura/docker-compose.yaml
    - name: Docker login
      docker_login:
        username: lepcloud23
        password: "{{docker_password}}"
    - name: Start containers from compose
      community.docker.docker_compose_v2:
        project_src: /home/laura
 