---
- name: Install Docker
  hosts: aws_ec2
  become: yes   
  tasks:
    - name: Make sure Docker is installed
      yum: 
        name: docker
        update_cache: yes
        state: present
    - name: Make sure docker daemon is running  
      systemd:
        name: docker
        state: started

- name: Install Docker-compose
  hosts: aws_ec2
  become: yes
  tasks:
    - name: docker-compose directory has been created
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install docker-compose
      get_url: 
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ remote_arch.stdout }}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x
